[workspace]
authors = ["michbelle <mi94bell@gmail.com>"]
channels = ["conda-forge"]
name = "remote_control_with_zenoh"
platforms = ["linux-64"]
version = "0.1.0"

[activation.env]
PATH = "$PATH:{root}/.pixi/envs/default/bin/go"

[tasks]
build_minica = "cd minica && go build"
gen_cert = "cd cert && ./../minica/minica --domains localhost"
build = "cmake -B build -S . && cmake --build build"

router = "zenohd -c ./config/router.json5"

sub = "./build/z_sub"
pub = "./build/z_pub"

[dependencies]
zenoh-pico = ">=1.8.0,<2"
go = ">=1.26.4,<2"
gcc_linux-64 = ">=14.3.0,<15"
gcc = ">=14.3.0,<14.4"
